version: '3.8'
services:
  database:
    image: mongo
    container_name: 'articlesland_cache_database'
    restart: always 
    ports:
      - "27017:27017"
    networks:
      - app-network
    logging:
      driver: none
    volumes: 
      - ~/.docker-data/articlesLand/mongo:/data/db
#    environment: 
#      - MONGO_INITDB_ROOT_USERNAME=lnftUser
#      - MONGO_INITDB_ROOT_PASSWORD=lnftlnftlnft

  server:
    container_name: 'articlesLand_cache_microservice'
    build: 
      context: ./
      dockerfile: Dockerfile
      target: dev
    volumes: 
      - /app/node_modules
      - ./:/app
      - ~/.docker-data/articlesLand/cache:/cache
    command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=30 -- npm run start:dev'
    environment:
      NODE_ENV: production
      AMQP_URL: amqp://rabbitmq:5672
    networks:
      - app-network
      - articlesLand-microservice-network

networks:
  app-network:
    driver: bridge
  articlesLand-microservice-network:
    external: true
